name: Publish PNPM Package

on:
  push:
    tags: "v*.*.*"

  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: "^9.15.4"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: |
          pnpm install --frozen-lockfile
          pnpm publish --access public --no-git-checks
